import React from "react";
import img1 from "../Images/1.webp";
import img2 from "../Images/2.webp";
import img3 from "../Images/3.webp";
import img4 from "../Images/4.webp";
import img5 from "../Images/5.webp";
import img6 from "../Images//6.webp";
import img7 from "../Images/7.webp";
import img8 from "../Images/8.webp";
import img9 from "../Images/9.webp";
import img10 from "../Images/10.webp";
import img11 from "../Images/11.webp";
import img12 from "../Images/12.webp";
import img13 from "../Images/13.webp";
import img14 from "../Images/14.webp";
import img15 from "../Images/15.webp";
import img16 from "../Images/16.webp";
import img17 from "../Images/17.webp";
import img18 from "../Images/18.webp";
import img19 from "../Images/19.webp";
import img20 from "../Images/20.webp";
import img21 from "../Images/21.webp";
import img22 from "../Images/22.webp";
import img23 from "../Images/23.webp";
import img24 from "../Images/24.webp";
import img25 from "../Images/25.webp";
import img26 from "../Images/26.webp";
import img27 from "../Images/27.webp";
import img28 from "../Images/28.webp";
import img29 from "../Images/29.webp";

export const Products = () => [
  {
    id: 1,
    name: "Belmont Custard Cream",
    description:
      "A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.",
    category: "Snacks",
    prevPrice: "$6.00",
    subCategory: "Nuts & Biscuits",
    price: "$5.00",
    ImageUrl: img1,
    weight: "1lb",
  },
  {
    id: 2,
    name: "Crawford Digestives",
    description:
      "A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.",
    category: "Snacks",
    subCategory: "Nuts & Biscuits",
    prevPrice: "$8.00",
    price: "$6.50",
    ImageUrl: img2,
    weight: ".75lb",
  },
  {
    id: 3,
    name: "Crawford Shortie",
    description:
      "A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.",
    category: "Snacks",
    subCategory: "Nuts & Biscuits",
    prevPrice: "$8.00",
    price: "$5.00",
    ImageUrl: img3,
    weight:"1lb"
  },
  {
    id: 4,
    name: "Hill Mini Pack Mix",
    description:
      "A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.",
    category: "Snacks",
    subCategory: "Nuts & Biscuits",
    prevPrice: "$10.00",
    price: "$7.50",
    ImageUrl: img4,
    weight: "1.2lb",
  },
  {
    id: 5,
    name: "Jammie Dodgers Raspberry",
    description: "A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.",
    category: "Snacks",
    subCategory: "Nuts & Biscuits",
    prevPrice: "$9.00",
    price: "$7.00",
    ImageUrl: img5,
    weight: "1lb",
  },
  {
    id: 6,
    name: "Juli S Cheese Crackers",
    description: "A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.",
    category: "Snacks",
    subCategory: "Nuts & Biscuits",
    prevPrice: "$8.00",
    price: "$5.00",
    ImageUrl: img6,
    weight: ".75lb",
  },
  {
    id: 7,
    name: "Khong Guan Orange Cream",
    description: "A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.",
    category: "Snacks",
    subCategory: "Nuts & Biscuits",
    prevPrice: "$8.00",
    price: "$5.00",
    ImageUrl: img7,
    weight: "0.5lb",
  },
  {
    id: 8,
    name: "Khong Guan Premium Marie",
    description: "A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.",
    category: "Snacks",
    subCategory: "Nuts & Biscuits",
    prevPrice: "$8.00",
    price: "$6.00",
    ImageUrl: img8,
    weight: "1lb",
  },
  {
    id: 9,
    name: "Lotus Biscoff",
    description: "A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.",
    category: "Snacks",
    subCategory: "Nuts & Biscuits",
    prevPrice: "$10.00",
    price: "$7.50",
    ImageUrl: img9,
    weight: "0.5lb",
  },
  {
    id: 10,
    name: "Filipinos",
    description: "Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.",
    category: "Snacks",
    subCategory: "Chocolates",
    prevPrice: "$5.00",
    price: "$4.00",
    ImageUrl: img10,
    weight: "0.5lb",
  },
  {
    id: 11,
    name: "Dairy Milk Crispello",
    description: "Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.",
    category: "Snacks",
    subCategory: "Chocolates",
    prevPrice: "$4.00",
    price: "$2.50",
    ImageUrl: img11,
    weight: ".4lb",
  },
  {
    id: 12,
    name: "Cadbury Zip",
    description: "Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.",
    category: "Snacks",
    subCategory: "Chocolates",
    prevPrice: "$4.00",
    price: "$2.90",
    ImageUrl: img12,
    weight: ".76lb",
  },
  {
    id: 13,
    name: "Dairy Milk Reclose",
    description: "Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.",
    category: "Snacks",
    subCategory: "Chocolates",
    prevPrice: "$4.50",
    price: "$3.50",
    ImageUrl: img13,
    weight: ".2lb",
  },
  {
    id: 14,
    name: "Cloetta Chocowoffle Crispy",
    description: "Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.",
    category: "Snacks",
    subCategory: "Chocolates",
    prevPrice: "$3.00",
    price: "$2.50",
    ImageUrl: img14,
    weight: "0.2lb",
  },
  {
    id: 15,
    name: "Cloetta Sprinkle",
    description: "Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.",
    category: "Snacks",
    subCategory: "Chocolates",
    prevPrice: "$4.00",
    price: "$3.00",
    ImageUrl: img15,
    weight: "0.2lb",
  },
  {
    id: 16,
    name: "Hersheys Kisses",
    description: "Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.",
    category: "Snacks",
    subCategory: "Chocolates",
    prevPrice: "$5.00",
    price: "$3.50",
    ImageUrl: img16,
    weight: "0.2lb",
  },
  {
    id: 17,
    name: "M & M Funsize",
    description: "Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.",
    category: "Snacks",
    subCategory: "Chocolates",
    prevPrice: "$2.00",
    price: "$1.00",
    ImageUrl: img17,
    weight: "0.1lb",
  },
  {
    id: 18,
    name: "Nestle Butterfinger",
    description: "Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.",
    category: "Snacks",
    subCategory: "Chocolates",
    prevPrice: "$1.30",
    price: "$1.00",
    ImageUrl: img18,
    weight: "0.1lb",
  },
  {
    id: 19,
    name: "Nestle Kitkat",
    description: "Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.",
    category: "Snacks",
    subCategory: "Chocolates",
    prevPrice: "$1.50",
    price: "$1.00",
    ImageUrl: img19,
    weight: "0.1lb",
  },
  {
    id: 20,
    name: "Snikers Slice",
    description: "Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.",
    category: "Snacks",
    subCategory: "Chocolates",
    prevPrice: "$4.00",
    price: "$3.00",
    ImageUrl: img20,
    weight: "0.1lb",
  },
  {
    id: 21,
    name: "Snikers Snack Size",
    description: "Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods.",
    category: "Snacks",
    subCategory: "Chocolates",
    prevPrice: "$3.60",
    price: "$3.00",
    ImageUrl: img21,
    weight: "0.1 lb",
  },
  {
    id: 22,
    name: "Wise Cottage Fires Bbq",
    description: "Potato chips (often just chips), or crisps, are thin slices of potato that have been deep fried or baked until crunchy. They are commonly served as a snack, side dish, or appetizer. The basic chips are cooked and salted; additional varieties are manufactured using various flavorings and ingredients including herbs, spices, cheeses, other natural flavors, artificial flavors, and additives.",
    category: "Snacks",
    subCategory: "Crisps",
    prevPrice: "$2.00",
    price: "$1.00",
    ImageUrl: img22,
    weight: "0.1lb",
  },
  {
    id: 23,
    name: "Puzzles Crips Ready Salted",
    description: "Potato chips (often just chips), or crisps, are thin slices of potato that have been deep fried or baked until crunchy. They are commonly served as a snack, side dish, or appetizer. The basic chips are cooked and salted; additional varieties are manufactured using various flavorings and ingredients including herbs, spices, cheeses, other natural flavors, artificial flavors, and additives.",
    category: "Snacks",
    subCategory: "Crisps",
    prevPrice: "$0.90",
    price: "$0.60",
    ImageUrl: img23,
    weight: "1lb",
  },
  {
    id: 24,
    name: "Doritos Tangy Cheese",
    description: "Potato chips (often just chips), or crisps, are thin slices of potato that have been deep fried or baked until crunchy. They are commonly served as a snack, side dish, or appetizer. The basic chips are cooked and salted; additional varieties are manufactured using various flavorings and ingredients including herbs, spices, cheeses, other natural flavors, artificial flavors, and additives.",
    category: "Snacks",
    subCategory: "Crisps",
    prevPrice: "$1.50",
    price: "$1.00",
    ImageUrl: img24,
    weight: ".76lb",
  },
  {
    id: 25,
    name: "Lays Baked",
    description: "Potato chips (often just chips), or crisps, are thin slices of potato that have been deep fried or baked until crunchy. They are commonly served as a snack, side dish, or appetizer. The basic chips are cooked and salted; additional varieties are manufactured using various flavorings and ingredients including herbs, spices, cheeses, other natural flavors, artificial flavors, and additives.",
    category: "Snacks",
    subCategory: "Crisps",
    prevPrice: "$2.50",
    price: "$1.50",
    ImageUrl: img25,
    weight: ".76lb",
  },
  {
    id: 26,
    name: "Lays Sea Salted",
    description: "Potato chips (often just chips), or crisps, are thin slices of potato that have been deep fried or baked until crunchy. They are commonly served as a snack, side dish, or appetizer. The basic chips are cooked and salted; additional varieties are manufactured using various flavorings and ingredients including herbs, spices, cheeses, other natural flavors, artificial flavors, and additives.",
    category: "Snacks",
    subCategory: "Crisps",
    prevPrice: "$1.60",
    price: "$1.20",
    ImageUrl: img26,
    weight: ".75lb",
  },
  {
    id: 27,
    name: "Lays Kettle Cooked",
    description: "Potato chips (often just chips), or crisps, are thin slices of potato that have been deep fried or baked until crunchy. They are commonly served as a snack, side dish, or appetizer. The basic chips are cooked and salted; additional varieties are manufactured using various flavorings and ingredients including herbs, spices, cheeses, other natural flavors, artificial flavors, and additives.",
    category: "Snacks",
    subCategory: "Crisps",
    prevPrice: "$2.00",
    price: "$1.00",
    ImageUrl: img27,
    weight: ".5lb",
  },
  {
    id: 28,
    name: "Lays Sour Cream",
    description: "Potato chips (often just chips), or crisps, are thin slices of potato that have been deep fried or baked until crunchy. They are commonly served as a snack, side dish, or appetizer. The basic chips are cooked and salted; additional varieties are manufactured using various flavorings and ingredients including herbs, spices, cheeses, other natural flavors, artificial flavors, and additives.",
    category: "Snacks",
    subCategory: "Crisps",
    prevPrice: "$1.90",
    price: "$1.50",
    ImageUrl: img28,
    weight: "0.1lb",
  },
  {
    id: 29,
    name: "Nims Apple Crisp",
    description: "Potato chips (often just chips), or crisps, are thin slices of potato that have been deep fried or baked until crunchy. They are commonly served as a snack, side dish, or appetizer. The basic chips are cooked and salted; additional varieties are manufactured using various flavorings and ingredients including herbs, spices, cheeses, other natural flavors, artificial flavors, and additives.",
    category: "Snacks",
    subCategory: "Crisps",
    prevPrice: "$2.00",
    price: "$1.50",
    ImageUrl: img29,
    weight: "0.1lb",
  },
];
